name: Build and Deploy to Pages

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    name: Build & deploy to GH Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21.6.1"
      - run: npm install
      - run: npm run build
      - run: cp CNAME build/CNAME
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build"
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
