name: Build and Deploy to Pages

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    name: Build & deploy to GH Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21.6.1"
      - run: npm run build
      - run: cp CNAME build/CNAME
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
